### ISSUE TITLE
Error in script start

### ISSUE THREAD

**Issue by aboutluca** [studiogustodev/3d-particles#1]
On start it gives error:
/Users/lucanardi/Desktop/3d-particles-master/src/index.js: Invalid Version: undefined

**Comment by luchoster** [comment]
why is this issue closed? 
is there a solution to fix that?

thanks

**Comment by aboutluca** [comment]
Ni, i switch to my usually bundler and it works!

**Comment by supahfunk** [comment]
I fixed that, sorry guys.
Please download the repo and reinstall it.
